version: 2
jobs:
  lint:
    golangci-lint:
      - image: golang:latest
    steps:
      - checkout
      - run: curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b ./bin
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.39.0
      - run: ./bin/golangci-lint run ./... | ./bin/reviewdog -f=golangci-lint -reporter=github-pr-review
