name: reviewdog
on: [pull_request]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      # optionally use a specific version of Go rather than the default one
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1.21.1
        with:
          workdir: golangci-lint/
          github_token: ${{ github.token }}
          reporter: "github-pr-review"
          fail_on_error: true

  stylelint:
    name: runner / stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
        working-directory: ./stylelint
      - name: stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          reporter: github-pr-review
          stylelint_input: '*.css'
          workdir: 'stylelint'
          fail_on_error: true
